function [t_final, angles_final, itr, Q_delX, reuse,...
    correspondences_reuse, dis_best_set]=MSAC(visible_edges,...
    angles_kalman, t_kalman, frame, edgeim, edgeim_next,...
    correspondences_reuse, dis_best_set, Q_delX, MinSegmentLength,...
    SearchLength, SearchLengthMSAC, SegmentLength, IRx, IRy, IPPM, f,...
    AccurateMode, MaxMSACRuns, MSACSampleSize, JumpOutAngle,...
    JumpoutTranslation, UseMahalanobis, MahalanobisDistance,... 
    PixelConvergenceThr, FastMode, ReusePixelThr, ReuseFactor,...
    CorrespondenceUpdates, ReuseData)
%% Assign R_kalman
R_kalman = makeR3(angles_kalman(1), angles_kalman(2), angles_kalman(3));
t_reuse = [];
angles_reuse =[];
reuse = 0;

%%
for itr=1:CorrespondenceUpdates % NUMBER of correspondence updates
    
    %% Create multiple correspondences
[correspondence_final]=create_correspondences_multiple(visible_edges,...
R_kalman, t_kalman, edgeim, MinSegmentLength, SearchLength,...
SegmentLength, IRx, IRy, IPPM, f);

    %% Remove outliers using MSAC or reuse correct correspondences from
    %last frame
if ReuseData
    if frame == 1
        [t_final, angles_final, R_final, stop_run, Q_delX, dis_best_set,...
         correspondences_reuse]=MSAC_robust(visible_edges,...
         angles_kalman, t_kalman, edgeim, correspondence_final,...
         Q_delX, MinSegmentLength, SearchLengthMSAC, SegmentLength,...
         IRx, IRy, IPPM, f, AccurateMode, MaxMSACRuns, MSACSampleSize,...
         JumpOutAngle, JumpoutTranslation, UseMahalanobis,...
         MahalanobisDistance, PixelConvergenceThr, FastMode);
    else
        [dis_best_set, reuse, t_reuse, angles_reuse, Q_delX,...
            correspondences_reuse]=temporal_reuse(correspondences_reuse,...
            R_kalman, t_kalman, edgeim_next, dis_best_set,...
            angles_kalman, Q_delX, visible_edges,  MinSegmentLength,...
            SearchLength, SegmentLength, IRx, IRy, IPPM, f,...
            ReusePixelThr, ReuseFactor);
        if reuse
            t_final = t_reuse;
            angles_final = angles_reuse;
            disp('reusing data')
            break;
        else
            [t_final, angles_final, R_final, stop_run, Q_delX,...
                dis_best_set, correspondences_reuse]=...
                MSAC_robust(visible_edges, angles_kalman,...
                t_kalman, edgeim, correspondence_final, Q_delX,...
                MinSegmentLength, SearchLengthMSAC, SegmentLength, IRx,...
                IRy, IPPM, f, AccurateMode, MaxMSACRuns, MSACSampleSize,...
                JumpOutAngle, JumpoutTranslation, UseMahalanobis,...
                MahalanobisDistance, PixelConvergenceThr, FastMode);
        end

    end
else
    [t_final, angles_final, R_final, stop_run, Q_delX, dis_best_set,...
        correspondences_reuse]=MSAC_robust(visible_edges,...
        angles_kalman, t_kalman, edgeim, correspondence_final, Q_delX,...
        MinSegmentLength, SearchLengthMSAC, SegmentLength, IRx, IRy,...
        IPPM, f, AccurateMode, MaxMSACRuns, MSACSampleSize,...
        JumpOutAngle, JumpoutTranslation, UseMahalanobis,...
        MahalanobisDistance, PixelConvergenceThr, FastMode);
end

%% Terminate MSAC if converged
    if stop_run
        break;
    end

%% Update correspondences
    disp('Updating correspondences')
    t_kalman=t_final;
    R_kalman=R_final;
    angles_kalman=angles_final;

end
end